#pragma kernel CSMain

RWTexture2D<float4> Result;

int Seed;

float rand(float2 co) {
    return(frac(sin(dot(co.xy, float2(12.9898, 78.233))) * 43758.5453)) * 1;
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float r = rand(float2(id.x * Seed, id.y * Seed));
    float g = rand(float2(id.y * Seed, id.x * Seed));
    float b = rand(float2(id.x / Seed, id.y * Seed));
    float a = rand(float2(id.x * Seed, id.y + Seed));

    Result[id.xy] = float4(r, g, b, a);
}
